# Generated by Django 4.1.4 on 2022-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_lisitings_bathrooms_lisitings_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lisitings", name="description", field=models.TextField(),
        ),
    ]
